module.exports = {
  BREAKING_BAD_CHARACTER_URL: 'https://www.breakingbadapi.com/api/characters',
  BREAKING_BAD_RANDOM_CHARACTER_URL: 'https://www.breakingbadapi.com/api/character/random',
  BREAKING_BAD_CHARACTER_TYPE: 'breakingbadcharacter',
  BREAKING_BAD_RANDOM_CHARACTER_TYPE: 'randombreakingbadcharacter',
  BREAKING_BAD_QUOTE_URL: 'https://breakingbadapi.com/api/quote',
  BREAKING_BAD_RANDOM_QUOTE_URL: 'https://breakingbadapi.com/api/quote/random',
  BREAKING_BAD_QUOTE_TYPE: 'breakingbadquote',
  BREAKING_BAD_RANDOM_QUOTE_TYPE: 'randombreakingbadquote',
  FINAL_SPACE_CHARACTER_URL: 'https://finalspaceapi.com/api/v0/character',
  POTTER_CHARACTER_URL: 'https://www.potterapi.com/v1/characters',
  POTTER_HOUSE_URL: 'https://www.potterapi.com/v1/houses',
  POTTER_SPELL_URL: 'https://www.potterapi.com/v1/spells',
  POTTER_CHARACTER_TYPE: 'character',
  POTTER_SPELL_TYPE: 'spell',
  OMDB_API_URL: 'http://www.omdbapi.com/',
  STAR_WARS_PEOPLE_URL: 'https://www.swapi.tech/api/people/',
  STAR_WARS_PLANETS_URL: 'https://www.swapi.tech/api/planets/',
  STAR_WARS_STARSHIPS_URL: 'https://www.swapi.tech/api/starships/',
  STAR_WARS_PEOPLE_TYPE : 'people',
  STAR_WARS_PLANETS_TYPE: 'planets',
  STAR_WARS_STARSHIPS_TYPE: 'starships'
};
